// Mock data for products
export const featuredProducts = [
    {
        id: 1,
        name: "Beach Bliss Flip-Flops",
        description:
            "Comfortable footwear for your beach days. These flip-flops are made with eco-friendly materials and provide excellent support for your feet.",
        price: 19.99,
        originalPrice: 29.99,
        images: ["/placeholder.svg?height=300&width=300"],
        category: "Shoes",
        condition: "Like new",
        size: "M",
        color: "Blue",
        brand: "EcoStep",
        seller: "Rahul Sharma",
        rating: 4.5,
        reviews: 12,
        createdAt: "2023-06-01",
        popularity: 85,
    },
    {
        id: 2,
        name: "Sunset Shades Sunglasses",
        description:
            "Stylish sunglasses with UV protection. Perfect for summer outings and beach days. The frame is lightweight and comfortable to wear all day.",
        price: 29.99,
        originalPrice: 45.99,
        images: ["/placeholder.svg?height=300&width=300"],
        category: "Accessories",
        condition: "New with tags",
        color: "Black",
        brand: "SunStyle",
        seller: "Priya Patel",
        rating: 5,
        reviews: 8,
        createdAt: "2023-05-15",
        popularity: 92,
    },
    {
        id: 3,
        name: "Cool Breeze Portable Fan",
        description:
            "Stay cool on hot summer days with this portable fan. It's rechargeable and can last up to 8 hours on a single charge.",
        price: 14.99,
        images: ["/placeholder.svg?height=300&width=300"],
        category: "Accessories",
        condition: "Good",
        color: "White",
        brand: "CoolTech",
        seller: "Amit Kumar",
        rating: 3.5,
        reviews: 5,
        createdAt: "2023-06-10",
        popularity: 78,
    },
    {
        id: 4,
        name: "Summer Breeze T-Shirt",
        description:
            "Lightweight cotton t-shirt perfect for summer. This breathable shirt keeps you cool and comfortable all day long.",
        price: 24.99,
        images: ["/placeholder.svg?height=300&width=300"],
        category: "Tops",
        condition: "Like new",
        size: "L",
        color: "White",
        brand: "ComfortWear",
        seller: "Neha Singh",
        rating: 4,
        reviews: 15,
        createdAt: "2023-05-20",
        popularity: 88,
    },
    {
        id: 5,
        name: "Sunset Beach Shorts",
        description: "Quick-dry swim shorts with vibrant sunset pattern. Perfect for beach days and pool parties.",
        price: 34.99,
        images: ["/placeholder.svg?height=300&width=300"],
        category: "Shorts",
        condition: "Good",
        size: "M",
        color: "Multi",
        brand: "BeachLife",
        seller: "Vikram Mehta",
        rating: 4.5,
        reviews: 7,
        createdAt: "2023-06-05",
        popularity: 82,
    },
    {
        id: 6,
        name: "Tropical Paradise Hawaiian Shirt",
        description: "Vibrant Hawaiian shirt with tropical print. Made from 100% cotton for maximum comfort.",
        price: 39.99,
        originalPrice: 59.99,
        images: ["/placeholder.svg?height=300&width=300"],
        category: "Tops",
        condition: "New with tags",
        size: "XL",
        color: "Multi",
        brand: "IslandStyle",
        seller: "Raj Malhotra",
        rating: 5,
        reviews: 3,
        createdAt: "2023-06-12",
        popularity: 75,
    },
    {
        id: 7,
        name: "Ocean Wave Swim Goggles",
        description: "Anti-fog swim goggles with UV protection. Perfect for swimming in pools and open water.",
        price: 12.99,
        images: ["/placeholder.svg?height=300&width=300"],
        category: "Accessories",
        condition: "Like new",
        color: "Blue",
        brand: "AquaVision",
        seller: "Ananya Desai",
        rating: 4,
        reviews: 9,
        createdAt: "2023-05-25",
        popularity: 80,
    },
    {
        id: 8,
        name: "Mountain Explorer Backpack",
        description: "Durable backpack with multiple compartments. Perfect for hiking and outdoor adventures.",
        price: 49.99,
        originalPrice: 79.99,
        images: ["/placeholder.svg?height=300&width=300"],
        category: "Accessories",
        condition: "Good",
        color: "Green",
        brand: "TrailBlazer",
        seller: "Arjun Kapoor",
        rating: 4.5,
        reviews: 11,
        createdAt: "2023-05-18",
        popularity: 87,
    },
]

// Generate more products for the all products list
export const allProducts = [
    ...featuredProducts,
    {
        id: 9,
        name: "Vintage Denim Jacket",
        description: "Classic denim jacket with a vintage wash. Perfect for layering in any season.",
        price: 59.99,
        images: ["/placeholder.svg?height=300&width=300"],
        category: "Tops",
        condition: "Good",
        size: "M",
        color: "Blue",
        brand: "DenimCo",
        seller: "Sanya Malhotra",
        rating: 4,
        reviews: 14,
        createdAt: "2023-04-10",
        popularity: 86
    },
    {
        id: 10,
        name: "Elegant Evening Dress",
        description: "Beautiful evening dress perfect for special occasions. Features delicate embroidery and a flattering silhouette.",
        price: 89.99,
        originalPrice: 149.99,
        images: ["/placeholder.svg?height=300&width=300"],
        category: "Women",
        condition: "Like new",
        size: "S",
        color: "Black",
        brand: "ElegantWear",
        seller: "Meera Sharma",
        rating: 5,
        reviews: 7,
        createdAt: "2023-03-15",
        popularity: 90
    },
    {
        id: 11,
        name: "Classic Leather Wallet",
        description: "Genuine leather wallet with multiple card slots and a coin pocket. Slim design fits comfortably in your pocket.",
        price: 39.99,
        images: ["/placeholder.svg?height=300&width=300"],
        category: "Accessories",
        condition: "Good",
        color: "Brown",
        brand: "LeatherCraft",
        seller: "Rohan Patel",
        rating: 4.5,
        reviews: 18,
        createdAt: "2023-05-05",
        popularity: 85
    },
    {
        id: 12,
        name: "Cozy Winter Sweater",
        description: "Warm knit sweater perfect for cold winter days. Made from a soft wool blend for maximum comfort.",
        price: 49.99,
        originalPrice: 79.99,
        images: ["/placeholder.svg?height=300&width=300"],
        category: "Tops",
        condition: "Like new",
        size: "L",
        color: "Gray",
        brand: "WinterWarm",
        seller: "Nisha Gupta",
        rating: 4,
        reviews: 9,
        createdAt: "2023-02-20",
        popularity: 82
    },
    {
        id: 13,
        name: "Sporty Running Shoes",
        description: "Lightweight running shoes with excellent cushioning. Perfect for jogging and everyday workouts.",
        price: 69.99,
        images: ["/placeholder.svg?height=300&width=300"],
        category: "Shoes",
        condition: "Good",
        size: "9",
        color: "Red",
        brand: "SpeedRun",
        seller: "Karan Khanna",
        rating: 4.5,
        reviews: 22,
        createdAt: "2023-04-25",
        popularity: 88
    },
    {
        id: 14,
        name: "Casual Denim Jeans",
        description: "Classic straight-leg jeans with a comfortable fit. Versatile for everyday wear.",
        price: 44.99,
        images: ["/placeholder.svg?height=300&width=300"],
        category: "Pants",
        condition: "Good",
        size: "32",
        color: "Blue",
        brand: "DenimCo",
        seller: "Aditya Sharma",
        rating: 4,
        reviews: 16,
        createdAt: "2023-03-30",
        popularity: 84
    },
    {
        id: 15,
        name: "Stylish Crossbody Bag",
        description: "Compact crossbody bag with multiple compartments. Perfect for carrying essentials while keeping your hands free.",
        price: 34.99,
        originalPrice: 54.99,
        images: ["/placeholder.svg?height=300&width=300"],
        category: "Accessories",
        condition: "Like new",
        color: "Black",
        brand: "UrbanStyle",
        seller: "Pooja Mehta",
        rating: 4.5,
        reviews: 13,
        createdAt: "2023-05-10",
        popularity: 87
    },
    {
        id: 16,
        name: "Formal Business Suit",
        description: "Professional two-piece suit perfect for business meetings and formal occasions.",
        price: 149.99,
        originalPrice: 249.99,
        images: ["/placeholder.svg?height=300&width=300"],
        category: "Men",
        condition: "Like new",
        size: "40R",
        color: "Navy",
        brand: "ExecutiveStyle",
        seller: "Rajesh Kumar",
        rating: 5,
        reviews: 8,
        createdAt: "2023-02-15",
        popularity: 86
    },
    {
        id: 17,
        name: "Cute Kids' Pajama Set",
        description: "Soft and comfortable pajama set for children. Features fun animal prints.",
        price: 19.99,
        images: ["/placeholder.svg?height=300&width=300"],
        category: "Kids",
        condition: "Good",
        size: "6T",
        color: "Multi",
        brand: "DreamyNights",
        seller: "Sneha Reddy",
        rating: 4.5,
        reviews: 11,
        createdAt: "2023-04-05",
        popularity: 83
    }
]

